// ============================================================================
// ARCHIVED -- NOT part of the active build. Nothing in the live codebase
// includes this file. See ARCHIVE_NOTE_mandelbrot_jump.md in this directory
// for the full story; short version below.
//
// STATUS: experimental, mechanistically sound, NULL RESULT.
// Rigorously A/B tested (puzzle 80, zone 82, n=10 baseline vs n=10
// Mandelbrot, zone pinned with -zone-force, zone_registry.bin/DP files
// wiped before every single run to remove all state confounds): mean K
// 0.857 vs 0.822, t ~= 0.19 -- not statistically distinguishable from no
// effect. An earlier batch appeared to show a large (~50%) improvement;
// that turned out to be a zone_registry.bin state-leak confound between
// batches, not a real effect -- it vanished once the confound was closed.
// Do not re-enable this expecting a speedup without re-running that A/B
// test yourself; nothing about the underlying math changed since this was
// tested clean and came up empty.
//
// What WAS real and worth knowing if anyone revives this: (1) EcJumps1's
// jump table, as generated by RCKangaroo.cpp's active default path, is
// magnitude-blind by index (i.i.d. draws, correlation(index, log2(size))
// ~= 0.07 on real data) -- this file's MAND_BUCKETS scheme assumed index
// order carried size information, which was false until a sort-by-
// magnitude step was added (also removed on archiving, was gated on
// g_use_mandelbrot in RCKangaroo.cpp). (2) A genuine multi-GPU bug was
// found and fixed during integration: a single shared LUT device pointer
// caused "illegal memory access" on every GPU but one -- device pointers
// are only valid on the GPU they were cudaMalloc'd on. If reviving this,
// keep the per-GPU LUT instance pattern (see the fixed version in git
// history / this file's own trailing comments below), don't reintroduce
// a single shared instance.
// ============================================================================

// mandelbrot_jump.h
// Pre-computed Mandelbrot LUT for jump selection
// Vectorized escape computation (SAS-style) — zero kernel overhead
//
// BIRTHDAY PARADOX: FULLY PRESERVED
//   - Both tame AND wild use identical LUT in GPU constant memory
//   - Same 512 jump points as standard — just selected differently
//   - Collision math unchanged: k = a + d_tame - d_wild
//   - LUT is stateless — no correlation between kangaroos
//
// PERFORMANCE:
//   - LUT pre-computed ONCE per zone change (vectorized, milliseconds)
//   - In kernel: single array lookup per jump — zero iteration overhead
//   - Standard: x & JMP_MASK (1 instruction)
//   - Mandelbrot: LUT[x & LUT_MASK] (1 instruction, same cost)
//
// ZONE INTEGRATION:
//   - Each zone maps to unique Mandelbrot slice (different Im value)
//   - LUT changes per zone — uploaded once per zone change
//   - Different zones = different jump weight distributions
//   - Fine coverage in boundary-rich zones, coarse in exterior zones

#pragma once
#include "defs.h"
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
// This header is included from BOTH nvcc-compiled .cu files (RCGpuCore.cu)
// AND plain g++-compiled .cpp files (CpuKang.cpp, CpuKang_JLP.cpp, via
// MandJumpSelect_CPU / MandelbrotLUT). cuda_runtime.h is host-includable
// (RCKangaroo.cpp/GpuKang.cpp already do this under g++) and declares
// cudaMalloc/cudaMemcpy/cudaFree/cudaSuccess/cudaMemcpyHostToDevice used
// by MandelbrotLUT below regardless of which compiler processes this file.
#include <cuda_runtime.h>

// ============================================================
// LUT dimensions
// 512 wide × 512 high = 262,144 entries
// Each entry: u16 jump index (0-511)
// Total size: 512KB — fits in GPU L2 cache
// ============================================================
#define MAND_LUT_W      512
#define MAND_LUT_H      512
#define MAND_LUT_SIZE   (MAND_LUT_W * MAND_LUT_H)
#define MAND_LUT_MASK   (MAND_LUT_W - 1)    // for x dimension
#define MAND_LUT_HMASK  (MAND_LUT_H - 1)    // for y dimension

#define MAND_MAX_ITER   64
#define MAND_ESCAPE_R2  4.0f
#define JMP_CNT_MAND    512     // must match JMP_CNT in defs.h

// Mandelbrot plane bounds
#define MAND_RE_MIN    -2.0f
#define MAND_RE_MAX     0.47f
#define MAND_IM_MIN    -1.12f
#define MAND_IM_MAX     1.12f

// ============================================================
// Jump scale buckets: escape time → jump size range (bits)
// ============================================================
struct MandBucket {
    int  iter_min, iter_max;   // escape time range
    int  bits_min, bits_max;   // jump size range in bits
    int  count;                // jumps allocated to this bucket
};

static const MandBucket MAND_BUCKETS[6] = {
    {  0,  8,  14, 24, 160 },  // deep/boundary → fine    35%
    {  8, 16,  24, 34, 120 },  // near boundary → local   23%
    { 16, 24,  34, 50,  90 },  // boundary zone → medium  16%
    { 24, 32,  50, 64,  70 },  // outer bound   → coarse  11%
    { 32, 48,  64, 72,  45 },  // escaping      → broad    7%
    { 48, 64,  72, 80,  27 },  // fast escape   → long     5%
};
// Total: 512 = JMP_CNT

// ============================================================
// Vectorized Mandelbrot escape — CPU, processes entire row
// SAS-style: iterate ALL points simultaneously, track which diverged
// ============================================================
static void MandEscapeRow_CPU(
    const float* c_re,    // array of real parts [MAND_LUT_W]
    float        c_im,    // imaginary part (same for whole row)
    int*         out_iter, // output escape times [MAND_LUT_W]
    int          n)        // = MAND_LUT_W
{
    float zr[MAND_LUT_W], zi[MAND_LUT_W];
    bool  done[MAND_LUT_W];

    // Initialize: z = 0, not done
    for (int i = 0; i < n; i++) {
        zr[i] = 0.0f; zi[i] = 0.0f;
        done[i] = false;
        out_iter[i] = MAND_MAX_ITER;
    }

    // Vectorized iteration — like SAS: iterate all simultaneously
    for (int it = 0; it < MAND_MAX_ITER; it++) {
        bool any_active = false;
        for (int i = 0; i < n; i++) {
            if (done[i]) continue;
            any_active = true;

            float zr2 = zr[i]*zr[i];
            float zi2 = zi[i]*zi[i];

            if (zr2 + zi2 > MAND_ESCAPE_R2) {
                out_iter[i] = it;
                done[i] = true;
                continue;
            }
            // z = z² + c
            zi[i] = 2.0f*zr[i]*zi[i] + c_im;
            zr[i] = zr2 - zi2 + c_re[i];
        }
        if (!any_active) break;
    }
}

// ============================================================
// Map escape time to jump table index
// Builds the jump → bucket mapping needed for LUT generation
// ============================================================
static void BuildJumpBucketMap(
    u16* jmp_to_bucket,   // output: which bucket each of 512 jumps belongs to
    u32* bucket_start,    // output: first jump index per bucket [6]
    u32* bucket_end)      // output: last+1 jump index per bucket [6]
{
    int idx = 0;
    for (int b = 0; b < 6; b++) {
        bucket_start[b] = (u32)idx;
        for (int j = 0; j < MAND_BUCKETS[b].count; j++) {
            if (idx < JMP_CNT_MAND)
                jmp_to_bucket[idx++] = (u16)b;
        }
        bucket_end[b] = (u32)idx;
    }
}

// ============================================================
// Build full Mandelbrot LUT for a specific zone
// Vectorized — processes all 512 rows using SAS-style approach
// Output: 512×512 array of jump indices (u16)
// ============================================================
static void BuildMandelbrotLUT(
    u16*  lut,          // output: [MAND_LUT_H][MAND_LUT_W] jump indices
    int   zone_id,      // 0-99
    int   range_bits)   // puzzle range bits
{
    printf("[MandLUT] Building zone %d LUT (%dx%d = %d entries)...\n",
           zone_id, MAND_LUT_W, MAND_LUT_H, MAND_LUT_SIZE);

    // Build jump bucket map
    u16 jmp_bucket[JMP_CNT_MAND] = {0};
    u32 b_start[6], b_end[6];
    BuildJumpBucketMap(jmp_bucket, b_start, b_end);

    // ------------------------------------------------------------------
    // CONTROL EXPERIMENT: MAND_FORCE_BUCKET=<0-5> env var skips the
    // Mandelbrot escape-time computation entirely and fills the WHOLE LUT
    // from one fixed bucket, uniformly at random within it. No fractal
    // math, no zone dependency -- this isolates whether an observed K
    // change comes from the escape-time/zone-shape story specifically, or
    // just from ANY hard skew toward one end of the now-magnitude-sorted
    // EcJumps1 table. Run this before trusting a real zone-weighted result:
    //   MAND_FORCE_BUCKET=0 ./rckangaroo ... -mandelbrot   (always "fine" -- smallest 160)
    //   MAND_FORCE_BUCKET=5 ./rckangaroo ... -mandelbrot   (always "long" -- largest 27)
    // If forcing a bucket reproduces the same K shift the real zone-82 LUT
    // showed, the effect isn't about Mandelbrot/escape-time at all -- it's
    // just "biasing away from Teske-optimal jump size does *something* in
    // this narrow zone-mode test", a much more mundane (and non-novel)
    // finding that needs its own separate explanation before it means
    // anything, let alone gets published as a fractal-jump-selection result.
    // ------------------------------------------------------------------
    {
        const char* force_env = getenv("MAND_FORCE_BUCKET");
        if (force_env != nullptr) {
            int b = atoi(force_env);
            if (b < 0) b = 0;
            if (b > 5) b = 5;
            u32 lo = b_start[b], hi = b_end[b];
            u32 rng = (u32)zone_id * 2654435761u + 999331u;
            printf("[MandLUT] MAND_FORCE_BUCKET=%d active -- filling ENTIRE LUT from bucket %d "
                   "(idx[%u:%u]) uniformly, NO escape-time computation, NO zone dependency\n",
                   b, b, lo, hi);
            for (int i = 0; i < MAND_LUT_SIZE; i++) {
                rng ^= rng << 13; rng ^= rng >> 17; rng ^= rng << 5;
                lut[i] = (u16)(lo + (hi > lo ? rng % (hi - lo) : 0));
            }
            printf("[MandLUT] Zone %d distribution: 100.0%% forced bucket %d, 0%% all others\n",
                   zone_id, b);
            return; // skip the real escape-time build below entirely
        }
    }

    // Pre-compute real part array (same for all rows)
    float c_re[MAND_LUT_W];
    for (int px = 0; px < MAND_LUT_W; px++) {
        c_re[px] = MAND_RE_MIN +
                   (MAND_RE_MAX - MAND_RE_MIN) * ((float)px / MAND_LUT_W);
    }

    // Map zone_id to imaginary range
    // Each zone gets a unique Im strip of the Mandelbrot plane
    float zone_frac = (float)zone_id / 100.0f;
    float im_center = MAND_IM_MIN +
                      (MAND_IM_MAX - MAND_IM_MIN) * zone_frac;
    float im_half   = (MAND_IM_MAX - MAND_IM_MIN) / 100.0f * 0.5f;

    // Simple PRNG for tie-breaking within bucket
    u32 rng = (u32)zone_id * 2654435761u + 1;
    auto rand_in = [&](u32 lo, u32 hi) -> u32 {
        rng ^= rng << 13; rng ^= rng >> 17; rng ^= rng << 5;
        return lo + rng % (hi - lo);
    };

    int iter_row[MAND_LUT_W];

    // ── SAS-style vectorized computation ─────────────────
    // Process all MAND_LUT_H rows, each row = one Im value
    for (int py = 0; py < MAND_LUT_H; py++) {
        float c_im = (im_center - im_half) +
                     (2.0f * im_half) * ((float)py / MAND_LUT_H);

        // Vectorized escape for entire row at once
        MandEscapeRow_CPU(c_re, c_im, iter_row, MAND_LUT_W);

        // Map each escape time to a jump index
        for (int px = 0; px < MAND_LUT_W; px++) {
            int t = iter_row[px];

            // Find bucket for this escape time
            int bucket = 5; // default: long jumps
            if      (t <  8) bucket = 0;
            else if (t < 16) bucket = 1;
            else if (t < 24) bucket = 2;
            else if (t < 32) bucket = 3;
            else if (t < 48) bucket = 4;
            else             bucket = 5;

            // Pick a random jump within that bucket
            // Use escape time + position for entropy
            u32 bucket_sz = b_end[bucket] - b_start[bucket];
            u32 offset = 0;
            if (bucket_sz > 0) {
                // Mix escape time, px, py for entropy
                u32 mix = (u32)(t*31 + px*17 + py*13);
                offset  = mix % bucket_sz;
            }
            lut[py * MAND_LUT_W + px] = (u16)(b_start[bucket] + offset);
        }
    }

    // Print bucket distribution summary
    int bucket_hist[6] = {0};
    for (int i = 0; i < MAND_LUT_SIZE; i++)
        bucket_hist[jmp_bucket[lut[i]]]++;

    printf("[MandLUT] Zone %d distribution:\n", zone_id);
    const char* names[6] = {"fine","local","medium","coarse","broad","long"};
    for (int b = 0; b < 6; b++)
        printf("[MandLUT]   %s: %.1f%%\n",
               names[b], 100.0f*bucket_hist[b]/MAND_LUT_SIZE);
}

// ============================================================
// GPU device: Use pre-computed LUT for jump selection
// Replaces: jmp_ind = Kx[0] & JMP_MASK
// With:     jmp_ind = MandJumpSelect(Kx[0], Kx[1], d_mand_lut)
//
// Cost: identical to standard (one memory read from constant cache)
//
// __CUDACC__-guarded: this file is included from plain g++-compiled .cpp
// files too (CpuKang.cpp, CpuKang_JLP.cpp), and __device__/__forceinline__/
// __restrict__ are CUDA-only language extensions g++ doesn't understand.
// Only nvcc defines __CUDACC__, so this block compiles out entirely under
// g++ — CPU files must use MandJumpSelect_CPU below instead.
// ============================================================
#ifdef __CUDACC__
__device__ __forceinline__ u32
MandJumpSelect(u64 x_lo, u64 x_hi, const u16* __restrict__ lut) {
    // Use low bits of x for LUT x-index
    u32 lut_x = (u32)(x_lo)         & MAND_LUT_MASK;
    // Use next bits for LUT y-index
    u32 lut_y = (u32)(x_lo >> 32)   & MAND_LUT_HMASK;
    return (u32)lut[lut_y * MAND_LUT_W + lut_x];
}
#endif // __CUDACC__

// ============================================================
// CPU-side equivalent, for CpuKang.cpp / CpuKang_JLP.cpp.
// Identical arithmetic to MandJumpSelect above — kept as a separate
// function (not shared) because __device__ code can't be called from
// plain .cpp translation units. Must be pointed at the HOST copy of the
// LUT (MandelbrotLUT::h_lut), never the device pointer d_lut — the CPU
// can't dereference GPU device memory directly.
// ============================================================
static inline u32
MandJumpSelect_CPU(u64 x_lo, u64 x_hi, const u16* lut) {
    u32 lut_x = (u32)(x_lo)       & MAND_LUT_MASK;
    u32 lut_y = (u32)(x_lo >> 32) & MAND_LUT_HMASK;
    return (u32)lut[lut_y * MAND_LUT_W + lut_x];
}

// ============================================================
// Host manager — handles LUT lifecycle
// ============================================================
class MandelbrotLUT {
public:
    u16*  h_lut;        // host LUT
    u16*  d_lut;        // device LUT (GPU)
    int   current_zone; // which zone the LUT is built for
    bool  initialized;

    MandelbrotLUT() : h_lut(nullptr), d_lut(nullptr),
                      current_zone(-1), initialized(false) {}

    bool Init() {
        h_lut = new u16[MAND_LUT_SIZE];
        if (cudaMalloc(&d_lut, MAND_LUT_SIZE * sizeof(u16)) != cudaSuccess) {
            printf("[MandLUT] cudaMalloc failed\n");
            return false;
        }
        initialized = true;
        return true;
    }

    // Call when zone changes — rebuilds and uploads LUT
    void UpdateZone(int zone_id, int range_bits) {
        if (zone_id == current_zone) return; // already current
        BuildMandelbrotLUT(h_lut, zone_id, range_bits);
        cudaMemcpy(d_lut, h_lut,
                   MAND_LUT_SIZE * sizeof(u16),
                   cudaMemcpyHostToDevice);
        current_zone = zone_id;
        printf("[MandLUT] Zone %d LUT uploaded to GPU\n", zone_id);
    }

    void Cleanup() {
        delete[] h_lut;
        if (d_lut) cudaFree(d_lut);
        initialized = false;
    }
};

// Global instances — defined in RCKangaroo.cpp.
// NOTE: originally a single shared g_mand_lut, changed to per-GPU because
// a device pointer (d_lut) allocated on one GPU is invalid on any other
// GPU -- sharing one caused "illegal memory access" on multi-GPU rigs.
// g_mand_lut_gpu[i] : one per GPU, device-side (d_lut valid only on GPU i)
// g_mand_lut_cpu    : one shared instance for CPU workers (h_lut only,
//                     no device-context restriction)
extern MandelbrotLUT g_mand_lut_gpu[MAX_GPU_CNT];
extern MandelbrotLUT g_mand_lut_cpu;

// ============================================================
// Actual integration (as wired, not the original sketch):
//
// defs.h — TKparams has: const u16* mand_lut; bool use_mandelbrot;
//
// RCGpuCore.cu — every jump-selection site (12 of them; see the
// integration checklist in project notes) calls the SelectJumpIndex()
// helper defined near the top of that file, which internally does:
//   Kparams.use_mandelbrot && Kparams.mand_lut
//     ? MandJumpSelect(x_lo, x_hi, Kparams.mand_lut)
//     : (x_lo & (JMP_CNT - 1))
//
// CpuKang.cpp / CpuKang_JLP.cpp — same pattern via SelectJumpIndexCPU(),
// reading g_mand_lut_cpu.h_lut instead of a device pointer.
//
// RCKangaroo.cpp — g_mand_lut_cpu built once (host-only, no device
// context dependency); g_mand_lut_gpu[i] built per-GPU inside the GPU
// prepare loop, AFTER that GPU's Prepare() call so cudaSetDevice(i) has
// already run -- do NOT build a single shared instance before the loop,
// its d_lut would only be valid on whichever GPU was "current" at that
// moment (this was a real bug: caused illegal memory access on every
// GPU but one on multi-GPU rigs).
//
// zone_id is g_active_zone_id (RCKangaroo.cpp), read by SolvePoint() at LUT-
// build time. For a plain (non-zone-mode) run it stays at its default of 0
// -- there's no operational zone concept there, so it's a fixed slice for
// the whole process, as before. For -zone-mode, zone_mode.cpp sets it to
// the real 0-99 zone_registry zone_id immediately before each SolvePoint()
// call, so each operational zone gets its own Mandelbrot slice (matching
// this file's original "each zone maps to a unique slice" design intent).
// IMPORTANT: this is a numeric coincidence, not a derived/validated
// mapping -- there's no proven reason zone_registry zone N's key-space
// range should correspond to Mandelbrot im-slice N. Treat it as an
// experimental knob, not an established result. Also: changing which
// zone_id maps to which LUT slice is a jump-function change, so any
// existing zone_dps_p*_z*.kangs file built under a different zone_id
// scheme is stale for zones other than 0 and must be deleted before
// re-testing -- same rule as any other change to jump selection.
//
// MAGNITUDE-BY-INDEX DEPENDENCY:
// MAND_BUCKETS above (and BuildJumpBucketMap) assume EcJumps1's index
// position correlates with jump magnitude (bucket 0 = "fine" = smallest,
// bucket 5 = "long" = largest). That assumption is FALSE for the table as
// generated by RCKangaroo.cpp's classic-uniform J1 loop (each of the 512
// entries is an i.i.d. random draw, independent of its index) -- verified
// empirically: correlation(index, log2(jump size)) ~= 0.07 (noise), all six
// buckets land on the same ~41.5-bit mean size on a puzzle-80 table despite
// claiming a 14-80 bit spread. Without a fix, this LUT's bucket weighting
// reorders selection over indices that carry no size information, so it
// cannot systematically favor coarse vs fine jumps no matter how the zone
// slice is chosen. RCKangaroo.cpp now sorts EcJumps1 by magnitude (gated on
// g_use_mandelbrot, right after the table is generated, before it's copied
// to any GPU) so index actually does correlate with size when -mandelbrot
// is on -- see the comment block there for why this is safe (uniform
// baseline selection is invariant to reordering; merge-consistency and
// cross-session resume are unaffected). EcJumps2/EcJumps3 are untouched --
// EcJumps2 isn't index-selected via SelectJumpIndex at all, and EcJumps3
// (the one Mandelbrot-selected site, KernelC's rare loop-escape jump)
// already gets a deliberately spread R2 magnitude assignment.
//
// Enable with: -mandelbrot flag
// ============================================================
